### ISSUE TITLE
import class from gradle

### ISSUE THREAD

**Issue by FunnyDevs** [stephanenicolas/morpheus#2]
hi! i have created a plugin module with ClassTransformer class. When i try to import this class on main app gradle file, i have
 
unable to resolve class com.example.plugin.ClassTransformer
 @ line 49, column 1.
   import com.example.plugin.ClassTransformer;
   ^

i have already added "compile project(':plugin')"

**Comment by stephanenicolas** [comment]
Sorry @funny devs, but this lib is not maintained anymore. You are really
on your own when using it.
All contributions welcome though.

2017-03-01 15:56 GMT+01:00 FunnyDevs <notifications@github.com>:

**Comment by FunnyDevs** [comment]
mmm ok. There is another tutorial / guide / plugin i can use to to add code in Android class file before dex process???
Thanks

**Comment by stephanenicolas** [comment]
The transform api is the official way to go.



2017-03-02 9:49 GMT+01:00 FunnyDevs <notifications@github.com>:

**Comment by FunnyDevs** [comment]
Ok,thank you
